name: Continuous Integration

# on:
#   push:
#     branches: [ main, dev ]
#   pull_request:
#     branches: [ main, dev ]

env:
  JAVA_VERSION: '11'
  JAVA_DISTRIBUTION: 'temurin'

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: ['11', '17', '21']
      fail-fast: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run tests
      run: mvn clean test

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-${{ matrix.os }}-java${{ matrix.java-version }}
        path: target/surefire-reports/

  code-quality:
    name: Code Quality Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run tests with coverage
      run: mvn clean test jacoco:report

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./target/site/jacoco/jacoco.xml
        flags: unittests
        name: codecov-umbrella

  build:
    name: Build Verification
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.JAVA_DISTRIBUTION }}

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build without tests
      run: mvn clean compile

    - name: Package JAR
      run: mvn package -DskipTests

    - name: Verify JAR integrity
      run: |
        JAR_FILE=$(find target -name "*-with-dependencies.jar" | head -1)
        if [ ! -f "$JAR_FILE" ]; then
          echo "JAR file not found!"
          exit 1
        fi
        
        # Verify JDBC driver class exists
        jar tf "$JAR_FILE" | grep "com/davydmaker/metabase/jdbc/MetabaseDriver.class" || {
          echo "Driver class not found in JAR"
          exit 1
        }
        
        # Verify MANIFEST and services are present
        jar tf "$JAR_FILE" | grep -E "(META-INF/MANIFEST.MF|META-INF/services/java.sql.Driver)" || {
          echo "Required META-INF files missing"
          exit 1
        }
        
        echo "JAR verification passed"
        ls -lh "$JAR_FILE" 
